# Generated by Django 2.2.4 on 2019-08-26 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('citizen_id', models.IntegerField()),
                ('town', models.CharField(default='', max_length=1000)),
                ('street', models.CharField(default='', max_length=1000)),
                ('building', models.CharField(default='', max_length=1000)),
                ('apartment', models.CharField(default='', max_length=1000)),
                ('name', models.CharField(default='', max_length=1000)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(default='', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('import_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='citizens.Citizen')),
                ('to_citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_people', to='citizens.Citizen')),
            ],
        ),
        migrations.AddField(
            model_name='citizen',
            name='import_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizens', to='citizens.Import'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='relatives',
            field=models.ManyToManyField(related_name='related_to', through='citizens.Relationship', to='citizens.Citizen'),
        ),
        migrations.AlterUniqueTogether(
            name='citizen',
            unique_together={('import_id', 'citizen_id')},
        ),
    ]
